import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useUpdateEmail } from "@/hooks/useEmailMutations";
import type { EmailResponse } from "@/types/api";

const schema = z.object({
  subject: z.string().min(1, "Subject is required").max(200, "Max 200 chars"),
  body_html: z.string().min(1, "HTML body is required"),
  body_text: z.string().min(1, "Plain text body is required"),
});

type FormValues = z.infer<typeof schema>;

interface EmailEditorProps {
  email: EmailResponse | null;
  campaignId: string;
  onClose: () => void;
}

export default function EmailEditor({
  email,
  campaignId,
  onClose,
}: EmailEditorProps) {
  const updateMutation = useUpdateEmail(campaignId);

  const form = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      subject: "",
      body_html: "",
      body_text: "",
    },
  });

  useEffect(() => {
    if (email) {
      form.reset({
        subject: email.subject,
        body_html: email.body_html,
        body_text: email.body_text,
      });
    }
  }, [email, form]);

  function onSubmit(values: FormValues) {
    if (!email) return;
    updateMutation.mutate(
      { id: email.id, data: values },
      { onSuccess: onClose },
    );
  }

  return (
    <Dialog
      open={email !== null}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Edit email</DialogTitle>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="subject"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Subject</FormLabel>
                  <FormControl>
                    <Input placeholder="Email subject" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Tabs defaultValue="html">
              <TabsList className="w-full">
                <TabsTrigger value="html" className="flex-1">
                  HTML
                </TabsTrigger>
                <TabsTrigger value="text" className="flex-1">
                  Plain Text
                </TabsTrigger>
                <TabsTrigger value="preview" className="flex-1">
                  Preview
                </TabsTrigger>
              </TabsList>

              <TabsContent value="html">
                <FormField
                  control={form.control}
                  name="body_html"
                  render={({ field }) => (
                    <FormItem>
                      <FormControl>
                        <Textarea
                          className="font-mono text-xs min-h-[240px]"
                          placeholder="<p>Email HTML body...</p>"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>

              <TabsContent value="text">
                <FormField
                  control={form.control}
                  name="body_text"
                  render={({ field }) => (
                    <FormItem>
                      <FormControl>
                        <Textarea
                          className="text-xs min-h-[240px]"
                          placeholder="Plain text version..."
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>

              <TabsContent value="preview">
                <div
                  className="min-h-[240px] rounded-md border bg-white dark:bg-zinc-950 p-4 text-sm overflow-auto"
                  // Email HTML is generated by our own LLM — not external user input
                  dangerouslySetInnerHTML={{
                    __html: form.watch("body_html"),
                  }}
                />
              </TabsContent>
            </Tabs>

            <DialogFooter>
              <Button type="button" variant="outline" onClick={onClose}>
                Cancel
              </Button>
              <Button type="submit" disabled={updateMutation.isPending}>
                {updateMutation.isPending ? "Saving…" : "Save changes"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
