"""add sender profile fields to users

Revision ID: bee75e0b3012
Revises: f000447e1a11
Create Date: 2026-06-18 17:48:23.219826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee75e0b3012'
down_revision: Union[str, Sequence[str], None] = 'f000447e1a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sender_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('sender_company', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sender_company')
    op.drop_column('users', 'sender_name')
    # ### end Alembic commands ###
